### ISSUE TITLE
Enhance Layer and Masking capabilities - This is amazing tool

### ISSUE THREAD

**Issue by kakachiex2** [erosDiffusion/ComfyUI-enricos-nodes#16]
Men you're a genius great tools how about implementing layers and support for mask, to mask area like in this composition
This is a mockup for a tool i have in mind and a canvas to visualize the layers comp.
![ComfyUI Layer Stack node-01](https://github.com/user-attachments/assets/ba014463-4c0e-4fd3-b1ec-843d415b9372)

**Comment by kakachiex2** [comment]
For example, this is your tool if you see I would like to mask the flag with the same hoodie mask as a clipping mask.
![Screenshot 2024-08-27 213038](https://github.com/user-attachments/assets/bcf05c28-e3ab-4bc4-b557-12a7ec34d3a5)

**Comment by kakachiex2** [comment]
Looks like there is a bug when I zoom out the image disappear

**Comment by erosDiffusion** [comment]
Hi @kakachiex2
- thanks for your ideas, your mock is really nice and in fact I had in mind something similar. I'am learning how to do code things in comfy so i'm not yet sure this is possible/easy to achive but I will look into it.  for masking I am using nodes from other suites. 
- for zindexing manipulation in the compositor is not straightforward I admin, expecially in complex cases and see how it can be improved.
- regarding the zoom out thanks for reporting the bug! It's a known issue and I think it's a limitation of Comfy. When zooming out a bit also other parts of all nodes, like text, disappear. I will check if it is possible to fix it and open a bug for it.

**Comment by kakachiex2** [comment]
Thanks for replaying good work on this tool keep it flowing..!

**Comment by erosDiffusion** [comment]
> Looks like there is a bug when I zoom out the image disappear

@kakachiex2 this is now fixed in the latest update.

**Comment by erosDiffusion** [comment]
masks (with auto apply) are coming with pr #26
clipping is possible but not yet planned.

**Comment by kakachiex2** [comment]
I have basic knowledge of coding HTML | CSS | JAVA SCRIPT in trying to recreate my layer node mockup in comfyui let see how far I can go.
