### ISSUE TITLE
Compositor not working

### ISSUE THREAD

**Issue by kakachiex2** [erosDiffusion/ComfyUI-enricos-nodes#3]
Prompt has no outputs
![Screenshot 2024-08-26 031457](https://github.com/user-attachments/assets/f75cc14e-0690-43ad-ad29-46dbca03236c)

**Comment by erosDiffusion** [comment]
Hi And thank you for the interest in this node.
the message means you need to attach an output like preview image.

after you run the node with the output attached the images pass will be visible in the compositor. initially your output will be black. you can arrange the composition and hit capture and run again. then your output will match the composition
![attach an output](https://github.com/user-attachments/assets/55466076-9092-4f5b-9412-f2be76ed88d4)
