### ISSUE TITLE
Save Composition State and reload on refresh

### ISSUE THREAD

**Issue by erosDiffusion** [erosDiffusion/ComfyUI-enricos-nodes#30]
As a user I would like to keep the composition state
- x,y, scale, skew, rotation
so that when I reload/re-execute the same flow
I will find the images in the same place i've placed them

acceptaince: save the info in the node as serialized json string and restore it on reload if possible.

**Comment by erosDiffusion** [comment]
fixed by #26

**Comment by LinkTree3** [comment]
I'm having this issue as well. the images loaded are losing their position after every reload, or moving from one workflow to another :(

Compositor v3 installed via the ComfyUI Manager under ComfyUI-enricos-nodes

**Comment by LinkTree3** [comment]
Hi thanks for the quick response! Yes it's indeed on ComfyUI windows portable version

**Comment by erosDiffusion** [comment]
> Hi thanks for the quick response! Yes it's indeed on ComfyUI windows portable version

@LinkTree3 so...within the same session, the thing I see is taht the previews are not rendered when switching tabs:
the positions are not actually lost,

infact if you switch tabs and re-eunqueue the node will rerun as it sees a fresh run and the canvas will re-generated with the existing transforms (see video). intermediate outputs from other nodes are not cached (the images are stored in a temp directory when produced and sent on the fly as base 64) in the compositor node.

Is this the problem you have or something different ?
for complete browser reload it's the same. the transient images (geerated by python and passed to compositor as tensors) are lost so you will need to rerun the flow. reason for not caching is that images are heavy and using non temp folders would spam your hd on every composition save with a new image.


https://github.com/user-attachments/assets/0684c54f-8281-47f6-86c6-aee299480e81
