### ISSUE TITLE
Node unresponsive after editing canvas again

### ISSUE THREAD

**Issue by sky958958** [erosDiffusion/ComfyUI-enricos-nodes#45]
hi~
Encountering a very strange problem, the first queue was successful,
But when I am not satisfied with the composition, I adjust the canvas and move the zoom, but the nodes cannot run again, the borders are red, and there is no response operation

**Comment by erosDiffusion** [comment]
it might have to do with an older node definition as v2 introduced some regressions but workarounds are possible

- can u try deleting the node and get a config and a compositor ? then run again ?
- to retrigger the run make play with the paused setting or any other configuration setting
- if that does not works and 
- if the border of the node (not inside the composition is red it means the output is not there usually, try hitting the capture button once images are loaded

i'm talking of v2
a screenshot and developer tools open (F12 and show the console tab) might help

**Comment by erosDiffusion** [comment]
so, i see some nulls in plugins and that index.js line 381 as red

- this could indicate that i'm not considering store tranform is false and then trying do do something with it.
so: make sure you have the latest code pulled, (from the custom node node directory you can "git fetch" and "git pull") 
- restart comfy, reload the flow, replace the nodes, set storetransforms and capture on queue to true and re-execute.



if that does not help:
- I would disable the three plugins that are mentioned here (mixlab, impact pack and use everywhere) as maybe one of them is incompatible. (I have all and see no issue)

let me know how it goes ;)


if you know how to debug, maybe click on that index.js 281 red line and show me it has anything to do with compositor. you can also give me the flow but i see it's pretty simple.

**Comment by erosDiffusion** [comment]
@sky958958 disable impact pack, leave capture on queue and transform on. the first time you execute it will block you as there is no reference so it assumes you want to change the composition. after you have ajusted (with no impact pack on) rerun, it should work.

**Comment by sky958958** [comment]
Looking forward to your update~Your node is really cool and convenient. Keep me away from those troublesome numerical settings

**Comment by erosDiffusion** [comment]
did it not work by disabling impact pack ?

to recap, I've had again some red line but re-triggering a second time seemed to fix it (maybe i'm blocking too much)
so...move, trigger red line, **retrigger* > runs..it's annoying , I will remove the blocker logic

**Comment by erosDiffusion** [comment]
I see, leave defaults on there should be no need to change them, when you get the red line, just push the enqueue button multiple times.

i hope this helps, sorry for the bad quality
https://github.com/user-attachments/assets/d0bb351c-6fa8-4dcb-8f4c-9aeae949d53a

**Comment by sky958958** [comment]
You have done an excellent job, it just takes time to maintain it. This node is the most anticipated one I have ever used

**Comment by erosDiffusion** [comment]
> ![image](https://private-user-images.githubusercontent.com/156326895/367323934-1cf6cab9-9a65-4611-a803-6f574b6e9d5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzcxMjcsIm5iZiI6MTcyNjIzNjgyNywicGF0aCI6Ii8xNTYzMjY4OTUvMzY3MzIzOTM0LTFjZjZjYWI5LTlhNjUtNDYxMS1hODAzLTZmNTc0YjZlOWQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNDEzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGU2MjU2NGY4YTcyYzkxZWY5NzlmOTQ4M2EwOTQyYTBjNTViNDY2M2UyZGE5NjZmNGQzMDYxODlhN2I4ZGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XOpf_v4GL9DvN-7Pd61nXibqVznMde_A9JigvKgINok) I don't understand technology, but I have an idea. For example, after adjusting the canvas, there is a control button below that can be clicked to directly trigger the subsequent workflow

in the new version it will come a button like "continue", that does what you ask.
I'm working on a wait function that's controlled by pause.

so when you pause the capture will read "continue" (technology wise continue is making the waiting thread move) while enqueue is re-submitting a slightly changed flow that's being stopped (old nodes dont' execute as they are cached)

pr #37 is a rewrite to solve the issues with inconsistent behaviur regarding execution.
i'm almost finished but i will not be able to work on it in the weekend :D

**Comment by sky958958** [comment]
Thank you for your video demonstration. Looking forward to your follow-up updates~Have a nice weekend~

**Comment by erosDiffusion** [comment]
should be fixed with v3 in pr #46
