### ISSUE TITLE
suggest setting it to reverse the mask.

### ISSUE THREAD

**Issue by cardenluo** [erosDiffusion/ComfyUI-enricos-nodes#56]
According to the current Mask detection Node . you would mask whatever needs editing, without having to add a reverse every time you perform a detection.
![image](https://github.com/user-attachments/assets/11c02965-a6ac-4656-bed1-82c3179325cd)

**Comment by erosDiffusion** [comment]
Hi @cardenluo , you are right, it's really annoying for me as well
it's on my roadmap to have a configuration for it. but I was thinking if it would be per input (requires a lot of space for the configuration) or global (just one switch)
Any opinion ?

**Comment by erosDiffusion** [comment]
@cardenluo  fixed in 3.0.5. try it out

**Comment by cardenluo** [comment]
very well  ,thanks ,the current logic is the true ”attention mask”.
