### ISSUE TITLE
Unable to output image after clicking continue

### ISSUE THREAD

**Issue by okamifish** [erosDiffusion/ComfyUI-enricos-nodes#68]
I've noticed something wierd, if I input two images, the composite image can be output successfully. But if one of the images is generated by a workflow, the image won't output correctly. Instead, clicking the "Continue" button, it just starts a new queue.

[Fisher compositor v3.json](https://github.com/user-attachments/files/17150043/Fisher.compositor.v3.json)

**Comment by erosDiffusion** [comment]
Hi there @okamifish . Please check the aviator issue in  the wiki. I can't check your wf now but it's likely the same issue. This is a limitation in comfy ui. I am working on real thread pause and it will come in a later release.

**Comment by okamifish** [comment]
> Hi there @okamifish . Please check the aviator issue in the wiki. I can't check your wf now but it's likely the same issue. This is a limitation in comfy ui. I am working on real thread pause and it will come in a later release. Kindly let me know if I can close the issue once you read that article.你好呀 。请检查 wiki 中的 aviator 问题。我现在无法检查你的 wf，但很可能是同样的问题。这是舒适用户界面的限制。我正在研究真正的线程暂停，它将在以后的版本中出现。当您阅读该文章后，请告诉我是否可以关闭该问题。

Yes, you're right. That's the same issue and I am sorry for not reading the Wiki carefully. Thanks.
