### ISSUE TITLE
Unable to automatically fit into the frame according to the preset width and height.

### ISSUE THREAD

**Issue by nhathoangfoto** [erosDiffusion/ComfyUI-enricos-nodes#69]
Even though I've resized the background and subject images to the same dimensions with identical width and height, what I need is for them to automatically fit precisely within the blue frame so that the image-to-image processes don't have any deviations in the canny edge or depth. I can move the layers manually, but it's not perfectly accurate.
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/dada95e9-0bda-4683-af99-d63cb40b83d3">

**Comment by erosDiffusion** [comment]
in the tools (add them and reload the screen) there is a centering option which will center all the objects in the frame (but not the group. 

initially it will look like this


![image](https://github.com/user-attachments/assets/8b0066fa-eb90-46e4-b0fd-c0046a3c3d5c)

**Comment by erosDiffusion** [comment]
@nhathoangfoto i will close the ticket for now and add new features for precise centering/positioning as feature request
