### ISSUE TITLE
为什么我的comfyUI找不到这个节点，管理器显示节点错误，但是修复没有用

### ISSUE THREAD

**Issue by gutouy** [erosDiffusion/ComfyUI-enricos-nodes#70]
为什么我的comfyUI找不到这个节点，管理器显示节点错误，但是修复没有用，并且节点文件夹中已经存在这个节点的文件夹
![1727587090699](https://github.com/user-attachments/assets/2d39554c-7dbe-4309-8859-8510fc0735c3)
![1727587125915](https://github.com/user-attachments/assets/7c31ef5d-e834-49d8-b984-d18fbebeffec)

![1727586975251](https://github.com/user-attachments/assets/829ff7e0-d9ff-47b3-bb22-6befe2420ee5)

**Comment by erosDiffusion** [comment]
@gutouy if you get this error, search again for compositor in the dropdown, you should find a new version.
re-open the ticket if this does not solve it
