### ISSUE TITLE
[Feature request] Using face-clone

### ISSUE THREAD

**Issue by razvanab** [erosDiffusion/ComfyUI-enricos-nodes#72]
A way to use ComfyUI-enricos-nodes with face-clone:
https://huggingface.co/h94/IP-Adapter-FaceID
https://github.com/ToTheBeginning/PuLID
https://github.com/TencentARC/PhotoMaker

**Comment by erosDiffusion** [comment]
could you elaborate on what you want to do exactly ?

**Comment by razvanab** [comment]
In the final render, I want to preserve the person's face. Consider the example image of the wolf and the warrior. I would like the output to retain the warrior's face from the input image.

**Comment by erosDiffusion** [comment]
You could use nodes that identify and mask faces. Florence2 clipseg or facedetailerson the output. If that's the goal

**Comment by razvanab** [comment]
I see. I never thought about it.
Thanks.

**Comment by erosDiffusion** [comment]
closing as it can be achieved without modifying the node
